Repository jisoo78/sesacproject, pull requests merged in 2024-12, with the labels that each got.

#1 feat : 크롤링 코드 생성
  hawhae.ipynb
Labels: crawling, Assignee ji, priority : high, merge

#3 feat : 크롤링2
  NLP.ipynb
Labels: crawling, Assignee ji

#5 feat : 데이터 프레임 형태소 확인
  NLP.ipynb
Labels: Assignee ji, Data preprocessing

#6 feat : 크롤링 변경 확인
  NLP.ipynb
Labels: crawling, Assignee ji

#7 feat : 크롤링 최종
  NLP.ipynb
Labels: crawling, Assignee ji

#9 feat : 전처리 사전 작업
  NLP.ipynb
Labels: crawling, preprocessing

#10 feat : 불용어 제거
  NLP.ipynb
Labels: preprocessing

#12 feat : 마스크 크롤링 코드
  mask.ipynb
  mask1_reviews_with_details.csv
  mask2_reviews_with_details.csv
  mask3_reviews_with_details.csv
  mask4_reviews_with_details.csv
  mask5_reviews_with_details.csv
Labels: crawling, Assignee so, priority : high, preprocessing

#13 feat : 선케어 크롤링 및 csv 파일 저장
  SunCare.ipynb
  suncare1_reviews_with_details.csv
  suncare2_reviews_with_details.csv
  suncare3_reviews_with_details.csv
  suncare4_reviews_with_details.csv
  suncare5_reviews_with_details.csv
Labels: crawling, Assignee ji, priority : high, preprocessing

#14 feat : 크롤링 및 csv 파일 저장
  cream.ipynb
  cream1_reviews_with_details.csv
  cream2_reviews_with_details.csv
  cream3_reviews_with_details.csv
  cream4_reviews_with_details.csv
  cream5_reviews_with_details.csv
  serum1_reviews_with_details.csv
  serum2_reviews_with_details.csv
  serum3_reviews_with_details.csv
  serum4_reviews_with_details.csv
  serum5_reviews_with_details.csv
Labels: crawling, Assignee hoon, priority : high, preprocessing

#21 feat : gemini 모델 생성
  .gitignore
  Model_GEMINI.ipynb
Labels: Assignee ji
